### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by abcoxyzide** [ernstlab/full_stack_ChromHMM_annotations#1]
Thank you for the amazing resource!

In file `state_annotations_processed.csv` there may be a spelling mistake, where "quiescent" is spelt as "quescient". The mneumonic seems alright though.

**Comment by havu73** [comment]
Hi @abcoxyzide ! Thank you so much for using our data and pointing out this spelling issues. I have fixed it and updated ```state_annotations_processed.csv```. I really appreciate it!
