### ISSUE TITLE
Overlapping annotations in hg38_genome_100_segments.bed

### ISSUE THREAD

**Issue by balwierz** [ernstlab/full_stack_ChromHMM_annotations#3]
Hi,
I found that there are cases where regions overlap. For instance the first line below overlaps with the 3 subsequent regions.
```
chr1    146261547       148712700       40_EnhWk6
chr1    146868566       146872566       1_GapArtf1
chr1    146872566       146872966       7_Quies4
chr1    146872966       146873766       1_GapArtf1
```

**Comment by havu73** [comment]
![image](https://github.com/ernstlab/full_stack_ChromHMM_annotations/assets/13281088/902e3103-c07b-4d40-8a13-9b38c529a75c)
<img width="468" alt="image" src="https://github.com/ernstlab/full_stack_ChromHMM_annotations/assets/13281088/20522cde-3d63-46bd-a130-d0003b17647b">
![image](https://github.com/ernstlab/full_stack_ChromHMM_annotations/assets/13281088/853b7a2e-4762-42df-8055-ee71e139ec55)

**Comment by havu73** [comment]
I typed my answer into a word document, and not sure why it does not allow pasting as text. So here is the link where you can download the hg38 chromatin state maps (please see above answer for the files that are of interests to you):
https://public.hoffman2.idre.ucla.edu/ernst/2K9RS//full_stack/full_stack_annotation_public_release/hg38

**Comment by havu73** [comment]
Hello! We have updated our readme with new links to the data, such that the problem of overlapping annotations are no longer present. Is it okay if we close this issue? We will keep it open in 3 days and then will close it!
